name: Count Files and Check README

on:
  push:
    branches:
      - main

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List .txt files
        run: |
          txt_files=$(find . -type f -name "*.txt")
          echo "Found ${txt_files}" >> txt_files_list.txt

      - name: Check README.md
        run: |
          if [ -f README.md ]; then
            echo "README.md exists"
          else
            echo "README.md does not exist"
          fi
